// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://comkrxhqfmonrtfbunym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvbWtyeGhxZm1vbnJ0ZmJ1bnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MjYxNzgsImV4cCI6MjA3ODAwMjE3OH0.zf7E87onTfGDDXlxRxeyLR2iGGZJfq8J6UiUTLRwMh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});